[build]
  command = "npm install --force && npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://tychem.net"
    prettyURLs = true
    trailingSlash = false
    exclude = [
      "/admin",
      "/admin/**"
    ]