[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://tychem.net"
    pretty = true
    trailingSlash = false
    exclude = [
      "/admin",
      "/admin/**"
    ]